export const productActionTypes = {
  SET_ACTIVE_PRODUCTS: "SET_ACTIVE_PRODUCTS",
  SET_FILTERED_PRODUCTS: "SET_FILTERED_PRODUCTS",
  SET_FEATURED_PRODUCTS: "SET_FEATURED_PRODUCTS",
  SET_MY_PRODUCTS: "SET_MY_PRODUCTS",
  SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
